// Animal page wrappers - each imports its unique LESS styling
import AnimalProfile from '../AnimalProfile'

// Import all animal LESS files for unique styling
import './GoldenRetriever.less'
import './Husky.less'
import './Poodle.less'
import './Bulldog.less'
import './Beagle.less'
import './Corgi.less'
import './Dalmatian.less'
import './Chihuahua.less'
import './Persian.less'
import './Siamese.less'
import './MaineCoon.less'
import './Bengal.less'
import './Ragdoll.less'
import './Sphynx.less'
import './BritishShorthair.less'
import './ScottishFold.less'
import './Parrot.less'
import './Canary.less'
import './Cockatiel.less'
import './Parakeet.less'
import './Macaw.less'
import './Finch.less'
import './Lovebird.less'
import './Dove.less'
import './Hamster.less'
import './Rabbit.less'
import './GuineaPig.less'
import './Ferret.less'
import './Turtle.less'
import './Iguana.less'
import './Hedgehog.less'
import './Chinchilla.less'
import './Goldfish.less'
import './Betta.less'
import './Koi.less'
import './Clownfish.less'
import './Seahorse.less'
import './Jellyfish.less'
import './Axolotl.less'
import './HermitCrab.less'

export default AnimalProfile
